require File.expand_path('commands/base', File.dirname(__FILE__))
require File.expand_path('commands/import', File.dirname(__FILE__))
require File.expand_path('commands/redact', File.dirname(__FILE__))
require File.expand_path('commands/sync', File.dirname(__FILE__))
require File.expand_path('commands/generate', File.dirname(__FILE__))
require File.expand_path('commands/git', File.dirname(__FILE__))
